### PR TITLE
Add sysmodule functionality

### PR DESCRIPTION
**Pull request by friedkeenan**
This should solve issue #2. It can build an nro and a kip from the same source: Run `make nro` or `make kip` to build each separately, or just run `make` to build them both.

### CODE REVIEW

**Comment by fennectech** [comment]
after compiling this it hangs on boot.

**Comment by friedkeenan** [comment]
I can reproduce the first bug, but not the second. Is telnet telling you "No route to host"? If so that's probably a problem with your router and not on the Switch's end. If it says "Connection refused" then it's probably the kip's fault

**Comment by friedkeenan** [comment]
Could you try loading the new version with sys-ftpd? It worked for me but I want to make sure

**Comment by friedkeenan** [comment]
Woops pressed the wrong button

**Comment by fennectech** [comment]
i have a freashly compiled (the other day) sys-ftpd  https://www.dropbox.com/s/1uhdzq5olr7fzmw/sys-ftpd.kip?dl=0  Here is a copy of my kip.

**Comment by fennectech** [comment]
Sysftpd is a modded one with auth enabled       fennectech and fennecnetwork are user/pass

**Comment by fennectech** [comment]
Itried loading the latest beta from the  releases page.   same result

**Comment by friedkeenan** [comment]
How many sysmodules are you loading? Sysmodules share their memory, so if you have too many it will hang on boot because they don't have enough memory

**Pull request merged**
